In [2]:
import torch
t = torch.tensor([[1,2,3]])
t

tensor([[1, 2, 3]])

In [3]:
t.T

tensor([[1],
        [2],
        [3]])

In [5]:
t@t.T

tensor([[14]])

(batch, seq_len, d_model) - standard Attention

(batch, num_heads, seq_len, head_dim) - multi-head attention

In [ ]:
import torch.nn.functional as F

def attention_block(query: torch.Tensor, key: torch.Tensor, values: torch.Tensor) -> torch.Tensor:
    dk = query.shape[-1]
    qk = (query @ key.transpose(-2,-1))/(dk**0.5)
    qk_sm = F.softmax(qk, dim=-1)
    return qk_sm @ values