In [1]:
import torch

## 1D + 2D -> 2D
"Single Axis broacasting"

In [15]:
t_rand = torch.rand((3,)) # Shape 1,3
print(t_rand)

tensor([0.6718, 0.1150, 0.4118])


In [26]:
t_rand.shape

torch.Size([3])

In [16]:
t_ones = torch.ones((4,1))
print(t_ones)

tensor([[1.],
        [1.],
        [1.],
        [1.]])


In [22]:
len(t_ones.shape)

2

In [17]:
torch.add(t_rand, t_ones)

tensor([[1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118]])

In [18]:
torch.add(t_ones, t_rand)

tensor([[1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118]])

In [30]:
t = torch.tensor([3])
print(t.item())

3


Multi-Axis Broadcasting

# torch sum(), torch.max(), torch.eq()

In [50]:
# torch.max(), torch.sum()
A = torch.tensor([[0,1,2], [0,2,3]]) # 2D tensor
B = torch.tensor([[4,0,5], [6,0,7]]) # 2D tensor
torch.sum(A==0, dim=0)

tensor([2, 0, 0])

In [40]:
torch.sum(torch.eq(A, 0), 0)

tensor([2, 0, 0])

In [41]:
zeros_per_col = torch.sum(A==0, dim=0)

In [42]:
torch.max(torch.sum(A==0, dim=0))

tensor(2)

In [43]:
max_num_0s = torch.max(zeros_per_col)

In [44]:
A[:,zeros_per_col != max_num_0s]

tensor([[1, 2],
        [2, 3]])

In [51]:
zeros_per_col_b = torch.sum(torch.eq(B, 0), dim=0)
torch.argmax(zeros_per_col_b)

tensor(1)

In [52]:
col_max_num_zeros_b = torch.argmax(zeros_per_col_b)
torch.cat([B[:, :col_max_num_zeros_b], B[:, col_max_num_zeros_b+1:]], dim=1)

tensor([[4, 5],
        [6, 7]])

These all fail because the shapes are not broadcastable. (after attempting to broadcast on both tensors)<br>
<img src="images/BT_exception_1.png" alt="Broadcasting Exception:" width="400"/>

in-place operations do not allow for broadcasting, but it seems we rarely encounter the need for in-place operations in Transformers and PyTorch Neural Networks:
<img src="images/BT_inplace.png" alt="in place BT" width="800"/>

https://docs.pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics

In [8]:
import torch
t = torch.tensor([[1,2,3], [2,4,6]])
torch.max(t,1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [29]:
torch.max(t,1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [22]:
torch.exp(norma_t)

tensor([[0.1353, 0.3679, 1.0000],
        [0.0183, 0.1353, 1.0000]])

In [24]:
torch.sum(t_expo, dim=1).view(-1,1)

tensor([[1.5032],
        [1.1537]])

In [25]:
torch.sum(t_expo, dim=1,keepdim=True)

tensor([[1.5032],
        [1.1537]])

In [27]:
torch.max(t,1,keepdim=True)

torch.return_types.max(
values=tensor([[3],
        [6]]),
indices=tensor([[2],
        [2]]))

In [21]:
norma_t = t - torch.max(t,1).values.view(-1,1)
t_expo = torch.exp(norma_t)