In [1]:
import torch

## 1D + 2D -> 2D
"Single Axis broacasting"

In [15]:
t_rand = torch.rand((3,)) # Shape 1,3
print(t_rand)

tensor([0.6718, 0.1150, 0.4118])


In [26]:
t_rand.shape

torch.Size([3])

In [16]:
t_ones = torch.ones((4,1))
print(t_ones)

tensor([[1.],
        [1.],
        [1.],
        [1.]])


In [22]:
len(t_ones.shape)

2

In [17]:
torch.add(t_rand, t_ones)

tensor([[1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118]])

In [18]:
torch.add(t_ones, t_rand)

tensor([[1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118],
        [1.6718, 1.1150, 1.4118]])

In [30]:
t = torch.tensor([3])
print(t.item())

3


Multi-Axis Broadcasting